name: homelab-iot-compose

networks:
  homelab-network:
    external: true

services:
  mosquitto:
    image: eclipse-mosquitto
    container-name: MQTT-Broker
    restart: unless-stopped
    ports:
      - ${MQTT_PORT:-1883}:1883
    volumes:
      - ${DATA_ROOT}/mosquitto/config:/mosquitto/config
      - ${DATA_ROOT}/mosquitto/data:/mosquitto/data
      - ${DATA_ROOT}/mosquitto/log:/mosquitto/log
    networks:
      homelab-network


  homelab-assistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container-name: HomeAssistant
    restart: unless-stopped
    privileged: true
    network-mode: host
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - ${DATA_ROOT}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro