name: Security Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: GitCheck Security Scan
        uses: Th3C0d3Mast3r/gitcheck@v1.0
        with:
          report_mode: '1'
