# hopefully, this should now work ig
name: Security Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: GitCheck Security Scan
        uses: docker://dcodemaster/gitcheck:latest
        with:
          report_mode: '1'
